# Generated by Django 4.0.6 on 2025-03-06 18:05

from django.db import migrations, models
import myauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=myauth.models.profile_avatar_dir_path),
        ),
    ]
