# Generated by Django 4.0.6 on 2025-03-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='avatar',
        ),
    ]
