# Generated by Django 4.0.6 on 2025-03-07 18:29

from django.db import migrations, models
import myauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_rename_photo_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='uploads/avatars/default.jpg', null=True, upload_to=myauth.models.profile_avatar_dir_path),
        ),
    ]
